-- ============================================================
-- 0001_init.sql — 基础表结构（幂等，可重复执行）
-- 执行方式：Supabase 控制台 → SQL Editor 粘贴执行
-- 兼容：posts/comments 已存在的旧表只会补列，不会丢数据
-- ============================================================

-- ---------- posts（文章） ----------
create table if not exists public.posts (
  id          bigint generated by default as identity primary key,
  author_id   uuid references auth.users(id) on delete set null,
  slug        text,
  title       text not null,
  content     text not null,
  excerpt     text,
  cover_image text,
  created_at  timestamptz not null default now(),
  published   boolean not null default false
);

-- 兼容旧表：补齐后加的列（无 NOT NULL，避免旧数据迁移失败）
alter table public.posts add column if not exists author_id uuid;
alter table public.posts add column if not exists slug text;
alter table public.posts add column if not exists excerpt text;
alter table public.posts add column if not exists cover_image text;

-- slug 唯一索引（若旧数据存在重复 slug，此句会报错，需先清理重复值）
create unique index if not exists posts_slug_key on public.posts (slug);

-- ---------- comments（评论） ----------
create table if not exists public.comments (
  id         bigint generated by default as identity primary key,
  post_id    bigint not null references public.posts(id) on delete cascade,
  name       text not null,
  content    text not null,
  created_at timestamptz not null default now()
);

-- ---------- profiles（用户资料，关联 auth.users） ----------
-- 博主标记 is_admin=true；后续 Phase 可扩展 username/bio/avatar 等字段
create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  is_admin   boolean not null default false,
  created_at timestamptz not null default now()
);

-- 默认权限（Supabase 通常已自动配置，显式声明以防缺漏）
grant select on public.posts, public.comments, public.profiles to anon, authenticated;
grant insert, update, delete on public.posts, public.comments, public.profiles to authenticated;
