-- ============================================================
-- 0005_phase3.sql — Phase 3：标签 / 浏览量 / 评论状态 / 搜索索引
-- 执行方式：Supabase 控制台 → SQL Editor 粘贴执行（幂等，可重复执行）
-- 前置：0001~0004 已执行（依赖 profiles 表与 public.is_admin() / public.ensure_profile()）
-- 评论模式：直接显示（新评论默认 approved 即时公开；博主可删除）
-- ============================================================

-- ---------- 1. 标签表 ----------
create table if not exists public.tags (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  slug       text not null unique,
  created_at timestamptz not null default now()
);

-- 文章-标签 关联表（多对多）
create table if not exists public.post_tags (
  post_id bigint not null references public.posts(id) on delete cascade,
  tag_id  bigint not null references public.tags(id) on delete cascade,
  primary key (post_id, tag_id)
);

-- ---------- 2. posts 浏览量列 ----------
alter table public.posts add column if not exists view_count int not null default 0;

-- ---------- 3. comments 状态列（直接显示模式：默认 approved） ----------
alter table public.comments add column if not exists status text not null default 'approved';

-- ---------- 4. 搜索索引（pg_trgm 模糊搜索加速） ----------
create extension if not exists pg_trgm;
create index if not exists posts_title_trgm_idx on public.posts using gin (title gin_trgm_ops);
create index if not exists posts_content_trgm_idx on public.posts using gin (content gin_trgm_ops);

-- ---------- 5. 浏览量递增 RPC（security definer，固定 +1，防任意改数） ----------
create or replace function public.increment_view(post_id bigint)
returns int
language sql
volatile
security definer
set search_path = public
as $$
  update public.posts set view_count = view_count + 1
  where id = post_id and status = 'published'
  returning view_count;
$$;

grant execute on function public.increment_view(bigint) to anon, authenticated;

-- ---------- 6. RLS ----------
alter table public.tags enable row level security;
alter table public.post_tags enable row level security;

-- tags：公开读，仅博主写
drop policy if exists "tags_select_public" on public.tags;
create policy "tags_select_public" on public.tags
  for select using (true);

drop policy if exists "tags_write_admin" on public.tags;
create policy "tags_write_admin" on public.tags
  for all using (public.is_admin()) with check (public.is_admin());

-- post_tags：公开读，仅博主写
drop policy if exists "post_tags_select_public" on public.post_tags;
create policy "post_tags_select_public" on public.post_tags
  for select using (true);

drop policy if exists "post_tags_write_admin" on public.post_tags;
create policy "post_tags_write_admin" on public.post_tags
  for all using (public.is_admin()) with check (public.is_admin());

-- 表级权限：新表必须显式 GRANT，否则 RLS 之前先被权限拒绝（42501）
grant select on public.tags, public.post_tags to anon, authenticated;
grant insert, update, delete on public.tags, public.post_tags to authenticated;

-- comments：直接显示模式（公开读、匿名可插入即时公开；博主可删的策略已在 0002 建立）
drop policy if exists "comments_select_public" on public.comments;
create policy "comments_select_public" on public.comments
  for select using (true);

drop policy if exists "comments_insert_public" on public.comments;
create policy "comments_insert_public" on public.comments
  for insert with check (true);
