-- ============================================================
-- 0011_guestbook.sql — 留言板（独立表 + RLS，匿名可发、仅博主可删）
-- 执行方式：Supabase 控制台 → SQL Editor 粘贴执行（幂等）
-- 参考 comments 的权限模式：任何人可读/可插入，删除走 is_admin()
-- ============================================================

create table if not exists public.guestbook_messages (
  id         bigint generated by default as identity primary key,
  name       text not null,
  content    text not null,
  ip         text,
  created_at timestamptz not null default now()
);

alter table public.guestbook_messages enable row level security;

-- 任何人可读
drop policy if exists "guestbook_select_public" on public.guestbook_messages;
create policy "guestbook_select_public" on public.guestbook_messages
  for select to anon, authenticated using (true);

-- 匿名可插入
drop policy if exists "guestbook_insert_public" on public.guestbook_messages;
create policy "guestbook_insert_public" on public.guestbook_messages
  for insert to anon, authenticated with check (true);

-- 仅博主可删
drop policy if exists "guestbook_delete_admin" on public.guestbook_messages;
create policy "guestbook_delete_admin" on public.guestbook_messages
  for delete to authenticated using (public.is_admin());

-- 表级权限
grant select, insert on public.guestbook_messages to anon, authenticated;
grant delete on public.guestbook_messages to authenticated;
