-- ============================================================
-- 0012_rag.sql — AI 问答 RAG：pgvector 扩展 + 文章分块向量表
-- 执行方式：Supabase 控制台 → SQL Editor 粘贴执行（幂等）
-- 依赖：is_admin()（0002 已建）
-- ============================================================

-- 1. 启用向量扩展
create extension if not exists vector;

-- 2. 文章分块表（post 删除级联清理分块）
create table if not exists public.article_chunks (
  id          bigint generated by default as identity primary key,
  post_id     bigint not null references public.posts(id) on delete cascade,
  chunk_index int not null,
  content     text not null,
  embedding   vector(1024) not null
);

-- 3. 向量索引（余弦相似度）
create index if not exists article_chunks_embedding_idx
  on public.article_chunks using ivfflat (embedding vector_cosine_ops);

-- 4. RLS：任何人可读；仅博主可写（索引同步在博主会话内执行）
alter table public.article_chunks enable row level security;

drop policy if exists "article_chunks_select_public" on public.article_chunks;
create policy "article_chunks_select_public" on public.article_chunks
  for select to anon, authenticated using (true);

drop policy if exists "article_chunks_insert_admin" on public.article_chunks;
create policy "article_chunks_insert_admin" on public.article_chunks
  for insert to authenticated with check (public.is_admin());

drop policy if exists "article_chunks_delete_admin" on public.article_chunks;
create policy "article_chunks_delete_admin" on public.article_chunks
  for delete to authenticated using (public.is_admin());

-- 5. 表级权限
grant select on public.article_chunks to anon, authenticated;
grant insert, delete on public.article_chunks to authenticated;
