-- ============================================================
-- 0013_messages.sql — 站内私信（独立表 + RLS）
-- 执行方式：Supabase 控制台 → SQL Editor 粘贴执行（幂等）
-- 权限模式：匿名可发（限流在 Server Action）；仅博主可读/可删
-- ============================================================

create table if not exists public.messages (
  id         bigint generated by default as identity primary key,
  name       text not null,
  contact    text,
  content    text not null,
  ip         text,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

-- 匿名可插入（写入不校验，Server Action 内做限流 + zod 校验）
drop policy if exists "messages_insert_public" on public.messages;
create policy "messages_insert_public" on public.messages
  for insert to anon, authenticated with check (true);

-- 仅博主可读（私信含联系方式，不公开）
drop policy if exists "messages_select_admin" on public.messages;
create policy "messages_select_admin" on public.messages
  for select to authenticated using (public.is_admin());

-- 仅博主可删
drop policy if exists "messages_delete_admin" on public.messages;
create policy "messages_delete_admin" on public.messages
  for delete to authenticated using (public.is_admin());

-- 表级权限
grant insert on public.messages to anon, authenticated;
grant select, delete on public.messages to authenticated;
